
import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { BookOpen, FileText, Layout, Lightbulb, MessageSquare, ChevronLeft, CheckCircle2, Brain, Bot, Clock, Users, Award, ChevronRight, PlayCircle, CheckCircle, Circle } from "lucide-react";
import Container from "@/components/ui/Container";
import { useToast } from "@/hooks/use-toast";
import { ChapterType, CourseType, FlashcardType, McqType, QnaType } from "@/types";
import AgentActivityPanel from "@/components/course/AgentActivityPanel";
import ChatMentor from "@/components/course/ChatMentor";
import NotebookPanel from "@/components/course/NotebookPanel";

const CourseDetail = () => {
  const { id } = useParams();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(true);
  const [course, setCourse] = useState<CourseType | null>(null);
  const [chapters, setChapters] = useState<ChapterType[]>([]);
  const [flashcards, setFlashcards] = useState<FlashcardType[]>([]);
  const [mcqs, setMcqs] = useState<McqType[]>([]);
  const [qnas, setQnas] = useState<QnaType[]>([]);
  const [activeTab, setActiveTab] = useState("chapters");
  const [selectedChapter, setSelectedChapter] = useState<string>("ch1");
  const [showAnswer, setShowAnswer] = useState<Record<string, boolean>>({});
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, string>>({});

  // Enhanced sample data with AI-generated content structure
  const sampleCourse: CourseType = {
    id: id || "1",
    user_id: "user123",
    title: "Advanced React Patterns and Performance Optimization",
    purpose: "job_interview",
    difficulty: "advanced",
    summary: "This comprehensive AI-generated course delves into advanced React patterns, architecture, and optimization techniques. Built by our Course Generation Agent with personalized learning paths, interactive mind maps, and intelligent recommendations.",
    created_at: new Date().toISOString(),
      content: {
        status: "complete",
        message: "Course generated by AI agents",
        lastUpdated: new Date().toISOString(),
        parsedContent: {
          summary: "AI-curated course covering advanced React concepts with personalized learning aids",
          chapters: [],
          flashcards: [],
          mcqs: [],
          qnas: [],
          mindMap: {
            root: {
              name: "Advanced React Patterns",
              type: "root",
              children: [
                {
                  name: "Component Patterns",
                  type: "concept",
                  children: [
                    {
                      name: "Compound Components",
                      type: "principle",
                      children: [
                        { name: "Shared State", type: "detail" },
                        { name: "Flexible API", type: "detail" }
                      ]
                    },
                    {
                      name: "Render Props",
                      type: "principle", 
                      children: [
                        { name: "Code Reuse", type: "example" },
                        { name: "Dynamic Rendering", type: "example" }
                      ]
                    }
                  ]
                },
                {
                  name: "Performance Optimization",
                  type: "best-practice",
                  children: [
                    { name: "React.memo", type: "optimization" },
                    { name: "useMemo & useCallback", type: "optimization" }
                  ]
                }
              ]
            }
          },
          notebook: {
            keyConcepts: [
              {
                term: "Higher-Order Component (HOC)",
                definition: "A function that takes a component and returns a new enhanced component with additional props or behavior",
                importance: "Essential for cross-cutting concerns like authentication, logging, and data fetching",
                examples: [
                  "withRouter for navigation props",
                  "withAuth for authentication checks"
                ]
              }
            ],
            analogies: [
              {
                concept: "Higher-Order Components",
                analogy: "Like a gift wrapper - you put a present (component) inside, and it comes out with beautiful wrapping (additional functionality)",
                explanation: "Just as a gift wrapper doesn't change the gift itself but enhances its presentation, HOCs enhance components without modifying their core functionality"
              }
            ],
            practicalTips: [
              "Start with simple patterns before moving to complex ones",
              "Always measure performance before and after optimizations"
            ]
          }
        }
      }
  };

  const sampleChapters: ChapterType[] = [
    {
      id: "ch1",
      course_id: id || "1",
      title: "React Component Patterns",
      content: `
# React Component Patterns

React offers various component patterns that help in creating reusable, maintainable, and optimized code. Here are the main patterns you should know:

## 1. Compound Components

Compound components are a pattern where components are composed together to share an implicit state while giving the user complete control over the rendering and composition of the components.

\`\`\`jsx
// Usage example
<Menu>
  <MenuButton>Options</MenuButton>
  <MenuList>
    <MenuItem>Download</MenuItem>
    <MenuItem>Create a Copy</MenuItem>
    <MenuItem>Delete</MenuItem>
  </MenuList>
</Menu>
\`\`\`

## 2. Render Props

Render Props is a technique for sharing code between components using a prop whose value is a function.

\`\`\`jsx
// Example
<DataProvider render={data => (
  <h1>Hello {data.target}</h1>
)}/>
\`\`\`

## 3. Higher-Order Components (HOCs)

HOCs are functions that take a component and return a new component with additional props or behavior.

\`\`\`jsx
// Example
const EnhancedComponent = withExtraProps(BaseComponent);
\`\`\`

## 4. Custom Hooks

Custom Hooks allow you to extract component logic into reusable functions.

\`\`\`jsx
// Example
function useFormInput(initialValue) {
  const [value, setValue] = useState(initialValue);
  
  function handleChange(e) {
    setValue(e.target.value);
  }
  
  return {
    value,
    onChange: handleChange
  };
}
\`\`\`

## 5. Control Props

Control Props give the parent component control over the internal state of a child component.

\`\`\`jsx
// Example
<Dropdown
  isOpen={isOpen}
  onToggle={setIsOpen}
  items={items}
/>
\`\`\`

Each pattern has its own use cases and trade-offs. Understanding when to use each pattern will help you design more flexible and maintainable React applications.
      `,
      order_number: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "ch2",
      course_id: id || "1",
      title: "Advanced State Management",
      content: `
# Advanced State Management in React

State management is one of the most critical aspects of building complex React applications. This chapter covers advanced state management techniques beyond simple useState.

## 1. Context API for Global State

React's Context API provides a way to share values like themes or user data without having to explicitly pass props through every level of the component tree.

\`\`\`jsx
// Creating a context
const ThemeContext = React.createContext('light');

// Provider component
function App() {
  return (
    <ThemeContext.Provider value="dark">
      <ThemedButton />
    </ThemeContext.Provider>
  );
}

// Consumer component
function ThemedButton() {
  const theme = useContext(ThemeContext);
  return <Button theme={theme} />;
}
\`\`\`

## 2. Redux and Redux Toolkit

Redux provides a predictable state container for JavaScript applications. Redux Toolkit is the official, opinionated toolset for efficient Redux development.

\`\`\`jsx
// Redux slice with Redux Toolkit
const counterSlice = createSlice({
  name: 'counter',
  initialState: { value: 0 },
  reducers: {
    incremented: state => {
      state.value += 1;
    },
    decremented: state => {
      state.value -= 1;
    }
  }
});
\`\`\`

## 3. Zustand

Zustand is a small, fast, and scalable state-management solution using simplified flux principles.

\`\`\`jsx
// Creating a store
const useStore = create(set => ({
  bears: 0,
  increasePopulation: () => set(state => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 })
}));
\`\`\`

## 4. React Query for Server State

React Query is a library for fetching, caching, and updating asynchronous data in React.

\`\`\`jsx
// Example usage
const { data, isLoading, error } = useQuery('todos', fetchTodos);
\`\`\`

## 5. Recoil

Recoil is an experimental state management library for React apps developed by Facebook.

\`\`\`jsx
// Defining an atom
const counterState = atom({
  key: 'counterState',
  default: 0,
});

// Using the atom
function Counter() {
  const [count, setCount] = useRecoilState(counterState);
  return (
    <>
      Count: {count}
      <button onClick={() => setCount(count + 1)}>Increment</button>
    </>
  );
}
\`\`\`

Understanding these state management techniques will help you choose the right solution for your specific use case, from simple component state to complex global state management.
      `,
      order_number: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "ch3",
      course_id: id || "1",
      title: "Performance Optimization Techniques",
      content: `
# Performance Optimization Techniques in React

Optimizing React applications is crucial for providing a smooth user experience. This chapter covers various techniques to improve the performance of your React applications.

## 1. Memoization with React.memo, useMemo, and useCallback

These React features help prevent unnecessary re-renders and recalculations.

\`\`\`jsx
// React.memo example
const MemoizedComponent = React.memo(function MyComponent(props) {
  // Only re-renders if props change
  return <div>{props.name}</div>;
});

// useMemo example
const memoizedValue = useMemo(() => computeExpensiveValue(a, b), [a, b]);

// useCallback example
const memoizedCallback = useCallback(() => {
  doSomething(a, b);
}, [a, b]);
\`\`\`

## 2. Code Splitting with React.lazy and Suspense

Code splitting allows you to split your code into small chunks that can be loaded on demand.

\`\`\`jsx
const OtherComponent = React.lazy(() => import('./OtherComponent'));

function MyComponent() {
  return (
    <React.Suspense fallback={<div>Loading...</div>}>
      <OtherComponent />
    </React.Suspense>
  );
}
\`\`\`

## 3. Virtualization for Long Lists

Virtualization renders only the visible items in a long list, significantly improving performance.

\`\`\`jsx
import { FixedSizeList } from 'react-window';

function VirtualizedList({ items }) {
  const Row = ({ index, style }) => (
    <div style={style}>
      {items[index]}
    </div>
  );

  return (
    <FixedSizeList
      height={500}
      width={300}
      itemCount={items.length}
      itemSize={35}
    >
      {Row}
    </FixedSizeList>
  );
}
\`\`\`

## 4. Web Workers for CPU-Intensive Tasks

Web Workers allow you to run JavaScript in background threads, keeping the UI responsive.

\`\`\`jsx
// Creating a worker
const worker = new Worker('./worker.js');

// Sending message to worker
worker.postMessage({ data: complexData });

// Receiving results from worker
worker.onmessage = function(e) {
  const result = e.data;
  setProcessedData(result);
};
\`\`\`

## 5. Bundle Size Optimization

Reducing bundle size improves loading times and overall performance.

- Use lightweight alternatives (e.g., Preact instead of React for simple apps)
- Tree shaking to eliminate dead code
- Dynamic imports for less frequently used features
- Analyze bundle with tools like Webpack Bundle Analyzer

\`\`\`jsx
// Dynamic import example
const loadAnalytics = () => import('./analytics');

button.addEventListener('click', async () => {
  const analytics = await loadAnalytics();
  analytics.trackClick();
});
\`\`\`

Implementing these optimization techniques will help you build React applications that are fast, responsive, and provide a great user experience even as the application grows in complexity.
      `,
      order_number: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const sampleFlashcards: FlashcardType[] = [
    {
      id: "f1",
      course_id: id || "1",
      question: "What is a Higher-Order Component (HOC) in React?",
      answer: "A Higher-Order Component is a function that takes a component and returns a new enhanced component with additional props or behavior. HOCs are a pattern derived from React's compositional nature and are used for cross-cutting concerns like state abstraction, code reuse, and props manipulation.",
      created_at: new Date().toISOString(),
    },
    {
      id: "f2",
      course_id: id || "1",
      question: "What is the purpose of React.memo?",
      answer: "React.memo is a higher-order component that memoizes the rendered output of a component, preventing unnecessary re-renders when the component's props haven't changed. It performs a shallow comparison of props by default but can be customized with a comparison function.",
      created_at: new Date().toISOString(),
    },
    {
      id: "f3",
      course_id: id || "1",
      question: "Explain the difference between useMemo and useCallback.",
      answer: "Both hooks are used for memoization, but useMemo caches the return value of a function, while useCallback caches the function instance itself. useMemo is used to avoid expensive calculations on every render, while useCallback is used to maintain referential equality of functions, which is important when passing callbacks to optimized child components.",
      created_at: new Date().toISOString(),
    },
    {
      id: "f4",
      course_id: id || "1",
      question: "What is the key difference between state and props in React?",
      answer: "Props are passed down from parent components and are read-only within the receiving component. State is managed within the component itself and can be updated using setState (class components) or state updater functions (hooks). Props represent external configuration, while state represents internal component state.",
      created_at: new Date().toISOString(),
    },
    {
      id: "f5",
      course_id: id || "1",
      question: "What is the React Context API used for?",
      answer: "The Context API provides a way to share values like themes, user data, or language preferences between components without explicitly passing props through every level of the component tree. It helps avoid 'prop drilling' in complex component hierarchies and is ideal for global state that many components need to access.",
      created_at: new Date().toISOString(),
    },
  ];

  const sampleMcqs: McqType[] = [
    {
      id: "m1",
      course_id: id || "1",
      question: "Which hook would you use to perform side effects in a function component?",
      options: ["useState", "useEffect", "useContext", "useReducer"],
      correct_answer: "useEffect",
      created_at: new Date().toISOString(),
    },
    {
      id: "m2",
      course_id: id || "1",
      question: "What is the correct way to update an object state in React using hooks?",
      options: [
        "setState(prevState.property = newValue)",
        "setState(prevState.property: newValue)",
        "setState({ ...prevState, property: newValue })",
        "setState(Object.assign(prevState, { property: newValue }))"
      ],
      correct_answer: "setState({ ...prevState, property: newValue })",
      created_at: new Date().toISOString(),
    },
    {
      id: "m3",
      course_id: id || "1",
      question: "In React, what happens when you call setState?",
      options: [
        "The component re-renders immediately",
        "The state object is changed immediately then the component re-renders",
        "The state update is queued, and React decides when to re-render for performance",
        "Nothing happens until you call forceUpdate()"
      ],
      correct_answer: "The state update is queued, and React decides when to re-render for performance",
      created_at: new Date().toISOString(),
    },
    {
      id: "m4",
      course_id: id || "1",
      question: "Which of the following is NOT a React hook?",
      options: ["useEffect", "useState", "useHistory", "useComponent"],
      correct_answer: "useComponent",
      created_at: new Date().toISOString(),
    },
    {
      id: "m5",
      course_id: id || "1",
      question: "What technique would you use to prevent a component from re-rendering when its parent re-renders but its props haven't changed?",
      options: [
        "shouldComponentUpdate lifecycle method",
        "React.memo higher-order component",
        "Pure components",
        "All of the above"
      ],
      correct_answer: "All of the above",
      created_at: new Date().toISOString(),
    },
  ];

  const sampleQnas: QnaType[] = [
    {
      id: "q1",
      course_id: id || "1",
      question: "What are some common performance issues in React applications and how would you diagnose them?",
      answer: "Common performance issues in React applications include:\n\n1. **Unnecessary re-renders**: Components re-rendering when they don't need to.\n2. **Large bundle sizes**: Initial load time is slow due to large JavaScript bundles.\n3. **Memory leaks**: Components or event listeners not being properly cleaned up.\n4. **Expensive calculations**: Performing heavy computations in render methods or during frequent state updates.\n5. **Network waterfalls**: Making sequential API calls instead of parallel ones.\n\nTo diagnose these issues:\n\n- Use React Developer Tools's Profiler to identify components that re-render too often or take too long to render.\n- Use the Performance tab in Chrome DevTools to analyze load time, JavaScript execution, and layout shifts.\n- Use Lighthouse for overall performance audits.\n- Use tools like Webpack Bundle Analyzer to identify large dependencies.\n- Use the Memory tab in Chrome DevTools to detect memory leaks.\n\nOnce issues are identified, solutions might include code splitting, memoization, virtualization for long lists, optimizing API calls, or refactoring component architecture.",
      created_at: new Date().toISOString(),
    },
    {
      id: "q2",
      course_id: id || "1",
      question: "Explain how you would architect a large-scale React application for maintainability and scalability.",
      answer: "Architecting a large-scale React application requires a thoughtful approach to code organization, state management, and team collaboration. Here's a comprehensive strategy:\n\n1. **Project Structure**:\n   - Feature-based or domain-driven folder structure instead of type-based\n   - Consistent naming conventions\n   - Clear separation between UI components, containers, hooks, and utilities\n   - Shared component library for design system implementation\n\n2. **State Management**:\n   - Use context + hooks for simpler global state\n   - Consider Redux (with Redux Toolkit) or MobX for complex state requirements\n   - Use React Query or SWR for server state\n   - Clear boundaries between local and global state\n\n3. **Code Splitting and Lazy Loading**:\n   - Route-based code splitting\n   - Component-based code splitting for large features\n   - Prioritize critical rendering path\n\n4. **Testing Strategy**:\n   - Unit tests for logic and utilities\n   - Component tests for UI behavior\n   - Integration tests for feature flows\n   - E2E tests for critical user journeys\n   - Clear testing patterns and utilities\n\n5. **Performance Optimization**:\n   - Memoization strategies (React.memo, useMemo, useCallback)\n   - Virtualization for long lists\n   - Image and asset optimization\n   - Strategic re-render prevention\n\n6. **Developer Experience**:\n   - Strong typing with TypeScript\n   - Comprehensive documentation\n   - Linting and formatting automation\n   - CI/CD pipeline for quality checks\n\n7. **Scalable Routing**:\n   - Nested routes for complex features\n   - Route-based code splitting\n   - Route guards for authentication/authorization\n\n8. **API Layer**:\n   - Centralized API client\n   - Response caching and request deduplication\n   - Error handling patterns\n   - Mock service workers for development\n\nThis architecture allows teams to work in parallel, keeps the codebase maintainable as it grows, and ensures good performance even as features are added.",
      created_at: new Date().toISOString(),
    },
    {
      id: "q3",
      course_id: id || "1",
      question: "What strategies would you use to optimize the performance of a React application that renders large datasets?",
      answer: "When dealing with large datasets in React, several optimization strategies can be employed:\n\n1. **Virtualization (Windowing)**:\n   - Use libraries like `react-window` or `react-virtualized` to render only the visible items\n   - Prevents rendering thousands of DOM nodes simultaneously\n   - Essential for lists with more than a few hundred items\n\n2. **Data Pagination and Infinite Scrolling**:\n   - Fetch and display data in chunks rather than all at once\n   - Implement infinite scrolling to load more data as the user scrolls\n   - Use cursor-based pagination for consistent performance\n\n3. **Memoization**:\n   - Use `React.memo` for pure components that render list items\n   - Apply `useMemo` for expensive derived calculations from data\n   - Implement `useCallback` for event handlers to maintain reference stability\n\n4. **State Management Optimization**:\n   - Consider normalized state shape to avoid duplication\n   - Use immutable data patterns for efficient change detection\n   - For Redux, implement selectors with Reselect for efficient derived data\n\n5. **Web Workers**:\n   - Offload heavy data processing to background threads\n   - Keep UI thread responsive while processing large datasets\n   - Libraries like `comlink` make working with Web Workers easier\n\n6. **Incremental Rendering**:\n   - Break rendering work into smaller chunks with time slicing\n   - Consider React 18's concurrent features and useTransition hook\n   - Prioritize critical updates over less important ones\n\n7. **Optimized Rendering Logic**:\n   - Avoid creating new objects/arrays in render\n   - Use stable keys for list items (not array index for dynamic lists)\n   - Prevent layout thrashing by batching DOM measurements and updates\n\n8. **Data Structure Selection**:\n   - Choose appropriate data structures for frequent operations (Maps for lookups, etc.)\n   - Pre-process and transform data outside of the render cycle when possible\n\n9. **Database Query Optimization**:\n   - Fetch only necessary fields (GraphQL can help here)\n   - Use server-side filtering, sorting, and aggregation\n   - Implement efficient backend pagination\n\nBy combining these strategies appropriately based on your specific use case, you can achieve smooth performance even with very large datasets.",
      created_at: new Date().toISOString(),
    },
  ];
  
  useEffect(() => {
    // In a real application, we would fetch data from the database
    // For this example, we're using the sample data
    setIsLoading(true);
    
    // Simulate API call delay
    const timer = setTimeout(() => {
      setCourse(sampleCourse);
      setChapters(sampleChapters);
      setFlashcards(sampleFlashcards);
      setMcqs(sampleMcqs);
      setQnas(sampleQnas);
      setIsLoading(false);
    }, 1000);
    
    return () => clearTimeout(timer);
  }, [id]);

  const toggleAnswer = (id: string) => {
    setShowAnswer(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const handleSelectAnswer = (id: string, option: string) => {
    setSelectedAnswers(prev => ({
      ...prev,
      [id]: option
    }));
  };

  const renderMarkdown = (content: string) => {
    if (!content) return '';
    
    // Enhanced HTML rendering for better course presentation
    return content
      .replace(/^#\s(.+)$/gm, '<h1 class="text-2xl font-bold mt-6 mb-4">$1</h1>')
      .replace(/^##\s(.+)$/gm, '<h2 class="text-xl font-bold mt-5 mb-3">$1</h2>')
      .replace(/^###\s(.+)$/gm, '<h3 class="text-lg font-bold mt-4 mb-2">$1</h3>')
      .replace(/^(?!<h[1-6]|<pre|<code|<ul|<ol|<li|<p|<blockquote)(.+)$/gm, '<p class="my-3">$1</p>')
      .replace(/\`\`\`(.+?)\n([\s\S]*?)\`\`\`/g, '<pre class="bg-muted p-4 rounded-md overflow-x-auto my-4"><code>$2</code></pre>')
      .replace(/\`([^\`]+)\`/g, '<code class="bg-muted px-1 py-0.5 rounded text-sm">$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/\*([^*]+)\*/g, '<em>$1</em>')
      .replace(/\n\n/g, '</p><p class="my-3">');
  };

  // Render loading state
  if (isLoading) {
    return (
      <Container className="py-12">
        <div className="animate-pulse space-y-8">
          <div className="h-8 bg-muted rounded w-1/3"></div>
          <div className="h-4 bg-muted rounded w-1/2"></div>
          <div className="h-64 bg-muted rounded"></div>
        </div>
      </Container>
    );
  }

  // If no course found
  if (!course) {
    return (
      <Container className="py-12">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4">Course not found</h1>
          <p className="mb-8 text-muted-foreground">The course you're looking for doesn't exist or has been removed.</p>
          <Button asChild>
            <Link to="/dashboard">Go to Dashboard</Link>
          </Button>
        </div>
      </Container>
    );
  }

  const formatLabel = (value: string) => {
    return value.replace(/_/g, ' ').replace(/\b\w/g, char => char.toUpperCase());
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header Section - Coursera Style */}
      <div className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-40">
        <Container className="py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link to="/dashboard" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary transition-colors">
                <ChevronLeft className="mr-1 h-4 w-4" />
                Back to Dashboard
              </Link>
              <Separator orientation="vertical" className="h-6" />
              <div className="flex items-center gap-2">
                <BookOpen className="h-5 w-5 text-primary" />
                <span className="font-medium text-foreground">Course</span>
              </div>
            </div>
            
            <div className="flex items-center gap-3">
              <Badge variant="secondary" className="px-3 py-1 font-medium">
                {formatLabel(course.difficulty)}
              </Badge>
              <Badge variant="outline" className="px-3 py-1">
                {formatLabel(course.purpose)}
              </Badge>
            </div>
          </div>
        </Container>
      </div>

      {/* Course Hero Section */}
      <div className="bg-gradient-to-br from-primary/5 via-background to-accent/5 border-b">
        <Container className="py-12">
          <div className="max-w-4xl">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-3 rounded-xl bg-primary/10 border border-primary/20">
                <Brain className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="text-sm font-medium text-primary">AI-Powered Learning Path</p>
                <p className="text-xs text-muted-foreground">Generated by advanced AI agents</p>
              </div>
            </div>
            
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6 bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">
              {course.title}
            </h1>
            
            {course.summary && (
              <p className="text-lg text-muted-foreground leading-relaxed mb-8 max-w-3xl">
                {course.summary}
              </p>
            )}
            
            <div className="flex items-center gap-6 text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4" />
                <span>~3 hours total</span>
              </div>
              <div className="flex items-center gap-2">
                <Users className="h-4 w-4" />
                <span>Advanced level</span>
              </div>
              <div className="flex items-center gap-2">
                <Award className="h-4 w-4" />
                <span>Certificate included</span>
              </div>
            </div>
          </div>
        </Container>
      </div>

      {/* Main Content Layout */}
      <div className="flex">
        {/* Sidebar Navigation - Coursera Style */}
        <div className="hidden lg:block w-80 border-r bg-background/50 backdrop-blur-sm">
          <div className="sticky top-24 h-[calc(100vh-6rem)] overflow-y-auto">
            <div className="p-6">
              <div className="mb-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-semibold text-foreground">Course Content</h3>
                  <Badge variant="outline" className="text-xs">
                    {chapters.length} modules
                  </Badge>
                </div>
                
                {/* Progress Overview */}
                <div className="bg-gradient-to-r from-primary/10 to-accent/10 rounded-xl p-4 mb-6">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-medium">Overall Progress</span>
                    <span className="text-sm font-bold text-primary">
                      {Math.round((chapters.findIndex(ch => ch.id === selectedChapter) + 1) / chapters.length * 100)}%
                    </span>
                  </div>
                  <div className="w-full bg-background rounded-full h-2">
                    <div 
                      className="bg-gradient-to-r from-primary to-accent h-2 rounded-full transition-all duration-500"
                      style={{ width: `${(chapters.findIndex(ch => ch.id === selectedChapter) + 1) / chapters.length * 100}%` }}
                    />
                  </div>
                  <p className="text-xs text-muted-foreground mt-2">
                    {chapters.findIndex(ch => ch.id === selectedChapter) + 1} of {chapters.length} modules completed
                  </p>
                </div>
              </div>
              
              {/* Chapter Navigation */}
              <div className="space-y-2">
                {chapters.map((chapter, index) => {
                  const isActive = selectedChapter === chapter.id;
                  const isCompleted = index < chapters.findIndex(ch => ch.id === selectedChapter);
                  
                  return (
                    <button
                      key={chapter.id}
                      onClick={() => setSelectedChapter(chapter.id)}
                      className={`w-full text-left p-4 rounded-lg border transition-all duration-200 hover:shadow-sm ${
                        isActive 
                          ? 'border-primary bg-primary/5 shadow-sm' 
                          : 'border-border hover:border-primary/30 hover:bg-accent/20'
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        <div className={`flex items-center justify-center w-6 h-6 rounded-full text-xs font-bold flex-shrink-0 mt-1 ${
                          isCompleted 
                            ? 'bg-green-500 text-white' 
                            : isActive 
                              ? 'bg-primary text-primary-foreground' 
                              : 'bg-muted text-muted-foreground'
                        }`}>
                          {isCompleted ? (
                            <CheckCircle className="h-3 w-3" />
                          ) : (
                            chapter.order_number
                          )}
                        </div>
                        
                        <div className="flex-1 min-w-0">
                          <h4 className={`font-medium text-sm leading-snug ${
                            isActive ? 'text-primary' : 'text-foreground'
                          }`}>
                            {chapter.title}
                          </h4>
                          <div className="flex items-center gap-2 mt-1">
                            <Clock className="h-3 w-3 text-muted-foreground" />
                            <span className="text-xs text-muted-foreground">15 min</span>
                          </div>
                        </div>
                        
                        <div className="flex items-center gap-1 flex-shrink-0">
                          {isActive && <PlayCircle className="h-4 w-4 text-primary" />}
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="flex-1 min-w-0">
          <div className="max-w-4xl mx-auto p-6 lg:p-8">
            <Tabs 
              defaultValue="chapters" 
              value={activeTab}
              onValueChange={setActiveTab}
              className="space-y-8"
            >
              <TabsList className="grid w-full grid-cols-4 max-w-lg h-12 bg-muted/50">
                <TabsTrigger value="chapters" className="flex items-center gap-2 text-sm">
                  <Layout className="h-4 w-4" />
                  Content
                </TabsTrigger>
                <TabsTrigger value="flashcards" className="flex items-center gap-2 text-sm">
                  <FileText className="h-4 w-4" />
                  Study
                </TabsTrigger>
                <TabsTrigger value="mcq" className="flex items-center gap-2 text-sm">
                  <CheckCircle2 className="h-4 w-4" />
                  Quiz
                </TabsTrigger>
                <TabsTrigger value="qna" className="flex items-center gap-2 text-sm">
                  <MessageSquare className="h-4 w-4" />
                  Q&A
                </TabsTrigger>
              </TabsList>
              
              {/* Chapter Content */}
              <TabsContent value="chapters" className="space-y-8">
                {chapters
                  .filter(chapter => chapter.id === selectedChapter)
                  .map((chapter) => (
                    <div key={chapter.id} className="space-y-8">
                      {/* Chapter Header */}
                      <div className="border rounded-xl p-8 bg-gradient-to-br from-background to-accent/5">
                        <div className="flex items-start justify-between mb-6">
                          <div className="flex-1">
                            <div className="flex items-center gap-3 mb-4">
                              <Badge variant="secondary" className="px-3 py-1 font-medium">
                                Module {String(chapter.order_number).padStart(2, '0')}
                              </Badge>
                              <div className="flex items-center gap-1 text-sm text-muted-foreground">
                                <Clock className="h-4 w-4" />
                                15 min read
                              </div>
                            </div>
                            
                            <h1 className="text-3xl font-bold tracking-tight mb-4">
                              {chapter.title}
                            </h1>
                            
                            <p className="text-muted-foreground text-lg leading-relaxed">
                              Deep dive into {chapter.title.toLowerCase()} and master the concepts that will elevate your development skills.
                            </p>
                          </div>
                        </div>
                        
                        {/* Learning Objectives */}
                        <div className="bg-primary/5 border border-primary/20 rounded-xl p-6">
                          <div className="flex items-center gap-3 mb-4">
                            <div className="p-2 rounded-lg bg-primary/10">
                              <Lightbulb className="h-5 w-5 text-primary" />
                            </div>
                            <h3 className="font-semibold text-foreground">Learning Objectives</h3>
                          </div>
                          <ul className="space-y-2 text-sm">
                            <li className="flex items-start gap-3">
                              <CheckCircle className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                              <span>Master advanced React patterns and their practical applications</span>
                            </li>
                            <li className="flex items-start gap-3">
                              <CheckCircle className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                              <span>Understand when and how to apply each pattern effectively</span>
                            </li>
                            <li className="flex items-start gap-3">
                              <CheckCircle className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                              <span>Build reusable and maintainable component architectures</span>
                            </li>
                          </ul>
                        </div>
                      </div>
                      
                      {/* Chapter Content */}
                      <div className="prose prose-lg max-w-none">
                        <div 
                          className="space-y-6 text-foreground"
                          dangerouslySetInnerHTML={{ __html: renderMarkdown(chapter.content) }}
                        />
                      </div>
                      
                      {/* Navigation */}
                      <div className="flex items-center justify-between pt-8 border-t">
                        <Button 
                          variant="outline" 
                          disabled={chapter.order_number === 1}
                          onClick={() => {
                            const prevChapter = chapters.find(ch => ch.order_number === chapter.order_number - 1);
                            if (prevChapter) setSelectedChapter(prevChapter.id);
                          }}
                          className="flex items-center gap-2"
                        >
                          <ChevronLeft className="h-4 w-4" />
                          Previous Module
                        </Button>
                        
                        <div className="flex items-center gap-3">
                          <span className="text-sm text-muted-foreground">
                            Module {chapter.order_number} of {chapters.length}
                          </span>
                        </div>
                        
                        <Button 
                          disabled={chapter.order_number === chapters.length}
                          onClick={() => {
                            const nextChapter = chapters.find(ch => ch.order_number === chapter.order_number + 1);
                            if (nextChapter) setSelectedChapter(nextChapter.id);
                          }}
                          className="flex items-center gap-2"
                        >
                          Next Module
                          <ChevronRight className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  ))}
              </TabsContent>
              
              {/* Flashcards Content */}
              <TabsContent value="flashcards" className="space-y-6">
                <div className="text-center py-8">
                  <div className="flex items-center justify-center mb-6">
                    <div className="p-4 rounded-full bg-primary/10">
                      <FileText className="h-8 w-8 text-primary" />
                    </div>
                  </div>
                  <h2 className="text-2xl font-bold mb-4">Study with Flashcards</h2>
                  <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
                    Reinforce your learning with AI-generated flashcards. Click on each card to reveal the answer.
                  </p>
                </div>
                
                <div className="grid gap-6 md:grid-cols-2">
                  {flashcards.map((flashcard) => (
                    <Card 
                      key={flashcard.id} 
                      className="cursor-pointer transition-all duration-200 hover:shadow-lg hover:scale-[1.02] border-2"
                      onClick={() => toggleAnswer(flashcard.id)}
                    >
                      <CardContent className="p-6">
                        <div className="mb-4">
                          <div className="flex items-center justify-between mb-3">
                            <Badge variant="outline" className="text-xs">
                              Flashcard
                            </Badge>
                            <Button 
                              variant="ghost" 
                              size="sm"
                              onClick={(e) => {
                                e.stopPropagation();
                                toggleAnswer(flashcard.id);
                              }}
                            >
                              {showAnswer[flashcard.id] ? 'Hide Answer' : 'Show Answer'}
                            </Button>
                          </div>
                          <h3 className="font-semibold mb-3 text-lg leading-snug">
                            {flashcard.question}
                          </h3>
                        </div>
                        
                        {showAnswer[flashcard.id] && (
                          <div className="border-t pt-4">
                            <div className="bg-primary/5 rounded-lg p-4">
                              <p className="text-foreground leading-relaxed">
                                {flashcard.answer}
                              </p>
                            </div>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </TabsContent>
              
              {/* MCQ Content */}
              <TabsContent value="mcq" className="space-y-6">
                <div className="text-center py-8">
                  <div className="flex items-center justify-center mb-6">
                    <div className="p-4 rounded-full bg-primary/10">
                      <CheckCircle2 className="h-8 w-8 text-primary" />
                    </div>
                  </div>
                  <h2 className="text-2xl font-bold mb-4">Test Your Knowledge</h2>
                  <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
                    Challenge yourself with these carefully crafted questions to assess your understanding.
                  </p>
                </div>
                
                <div className="space-y-8">
                  {mcqs.map((mcq, index) => (
                    <Card key={mcq.id} className="border-2">
                      <CardContent className="p-6">
                        <div className="mb-6">
                          <div className="flex items-center gap-3 mb-4">
                            <Badge variant="secondary" className="px-3 py-1">
                              Question {index + 1}
                            </Badge>
                          </div>
                          <h3 className="text-lg font-semibold leading-snug">
                            {mcq.question}
                          </h3>
                        </div>
                        
                        <div className="space-y-3">
                          {mcq.options.map((option, optionIndex) => {
                            const isSelected = selectedAnswers[mcq.id] === option;
                            const isCorrect = option === mcq.correct_answer;
                            const showResult = selectedAnswers[mcq.id];
                            
                            return (
                              <button
                                key={optionIndex}
                                onClick={() => handleSelectAnswer(mcq.id, option)}
                                className={`w-full text-left p-4 rounded-lg border-2 transition-all duration-200 ${
                                  showResult
                                    ? isCorrect
                                      ? 'border-green-500 bg-green-50 dark:bg-green-950'
                                      : isSelected
                                        ? 'border-red-500 bg-red-50 dark:bg-red-950'
                                        : 'border-border bg-background'
                                    : isSelected
                                      ? 'border-primary bg-primary/5'
                                      : 'border-border hover:border-primary/50 hover:bg-accent/30'
                                }`}
                              >
                                <div className="flex items-center gap-3">
                                  <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center text-xs font-bold ${
                                    showResult
                                      ? isCorrect
                                        ? 'border-green-500 bg-green-500 text-white'
                                        : isSelected
                                          ? 'border-red-500 bg-red-500 text-white'
                                          : 'border-muted-foreground'
                                      : isSelected
                                        ? 'border-primary bg-primary text-primary-foreground'
                                        : 'border-muted-foreground'
                                  }`}>
                                    {String.fromCharCode(65 + optionIndex)}
                                  </div>
                                  <span className="flex-1 font-medium">{option}</span>
                                  {showResult && isCorrect && (
                                    <CheckCircle className="h-5 w-5 text-green-500" />
                                  )}
                                </div>
                              </button>
                            );
                          })}
                        </div>
                        
                        {selectedAnswers[mcq.id] && (
                          <div className="mt-6 pt-4 border-t">
                            <div className={`p-4 rounded-lg ${
                              selectedAnswers[mcq.id] === mcq.correct_answer
                                ? 'bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800'
                                : 'bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800'
                            }`}>
                              <p className={`font-medium ${
                                selectedAnswers[mcq.id] === mcq.correct_answer
                                  ? 'text-green-800 dark:text-green-200'
                                  : 'text-red-800 dark:text-red-200'
                              }`}>
                                {selectedAnswers[mcq.id] === mcq.correct_answer
                                  ? '✓ Correct!'
                                  : '✗ Incorrect'
                                }
                              </p>
                              {selectedAnswers[mcq.id] !== mcq.correct_answer && (
                                <p className="text-sm text-muted-foreground mt-1">
                                  The correct answer is: <strong>{mcq.correct_answer}</strong>
                                </p>
                              )}
                            </div>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </TabsContent>
              
              {/* Q&A Content */}
              <TabsContent value="qna" className="space-y-6">
                <div className="text-center py-8">
                  <div className="flex items-center justify-center mb-6">
                    <div className="p-4 rounded-full bg-primary/10">
                      <MessageSquare className="h-8 w-8 text-primary" />
                    </div>
                  </div>
                  <h2 className="text-2xl font-bold mb-4">Interview Preparation</h2>
                  <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
                    Practice with real interview questions and detailed answers to prepare for technical discussions.
                  </p>
                </div>
                
                <Accordion type="single" collapsible className="space-y-4">
                  {qnas.map((qna, index) => (
                    <AccordionItem key={qna.id} value={qna.id} className="border rounded-xl">
                      <AccordionTrigger className="px-6 py-4 hover:no-underline hover:bg-accent/30 rounded-t-xl">
                        <div className="flex items-start gap-4 text-left">
                          <Badge variant="outline" className="mt-1 px-2 py-1 text-xs">
                            Q{index + 1}
                          </Badge>
                          <span className="font-semibold text-lg leading-snug">
                            {qna.question}
                          </span>
                        </div>
                      </AccordionTrigger>
                      <AccordionContent className="px-6 pb-6">
                        <div className="bg-accent/20 rounded-lg p-6 mt-4">
                          <div 
                            className="prose max-w-none text-foreground"
                            dangerouslySetInnerHTML={{ __html: renderMarkdown(qna.answer) }}
                          />
                        </div>
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </TabsContent>
            </Tabs>
          </div>
        </div>
        
        {/* Right Sidebar - AI Coach */}
        <div className="hidden xl:block w-80 border-l bg-background/50 backdrop-blur-sm">
          <div className="sticky top-24 h-[calc(100vh-6rem)] flex flex-col">
            <div className="p-6 border-b">
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Bot className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold">AI Learning Coach</h3>
                  <p className="text-sm text-muted-foreground">Get personalized help</p>
                </div>
              </div>
            </div>
            
            <div className="flex-1 flex flex-col">
              <div className="flex-1 p-6">
                <ChatMentor userId="user123" />
              </div>
              
              <div className="p-6 border-t space-y-4">
                <AgentActivityPanel userId="user123" />
                <NotebookPanel 
                  notebook={course?.content?.parsedContent?.notebook || { keyConcepts: [], analogies: [], practicalTips: [] }}
                  mindMap={course?.content?.parsedContent?.mindMap}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CourseDetail;
